source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!


install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

workspace 'Hearthstone'

target 'Hearthstone' do
    pod 'SwiftLint'
    
    pod 'AlamofireImage'
    
    target 'HearthstoneTests' do
        inherit! :search_paths
    end
end
