# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def shared_pods
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'RealmSwift'
    pod 'SDWebImage', '~> 4.0'
    pod 'ScalingCarousel'    
end

target 'HearthstoneAssessmentApp' do
  shared_pods
end
